language: node_js

cache:
  directories:
    - node_modules

notifications:
  email: false

node_js:
  - '8'

before_script:
  - lerna bootstrap --concurrency=1

after_success:
  - ./publish.sh

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+(\\-.*)?$/"
